language: "python"
python: "2.7"
sudo: false
cache: pip
install:
   - pip install pycodestyle
   - pip install -r requirements.txt
   - pip install -r test/requirements.txt
   - pip install coveralls
before_script:
   - cp vmbot/example/config.py ./
   - python -c "from vmbot.helpers import database as db; db.init_db()"
script:
   - pycodestyle --max-line-length=100 --ignore=W503,W606 --exclude=jabberbot.py vmbot/
   - pycodestyle --max-line-length=100 --ignore=W503,W606 tools/
   - pycodestyle --max-line-length=100 --ignore=W503,W606 test/
   - coverage run -m unittest discover
after_success: coveralls
after_script: coverage report
